### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-cloud-openshift-operator#28]
Primary considerations:

- Consistency with https://openliberty.io/guides/cloud-openshift.html: This guide should be consistent with what we have in the guide-cloud-openshift guide.  Should call out how users get to an OpenShift cluster and start working with it.

- What's the intention of the Kafka section and the benefits of using Operators when you have such dependencies?  Please clarify.

Additional considerations:

- Call out the benefits of using Operators -- in this case, the OL Operator -- in the Intro section

- " Ensure you are using version 4.x because the Dockerfiles used in this guide use the --chown flag, which is incompatible with older versions of Docker": Can't parse this easily.  The 4.x version is referring to what?

- "Make sure to run all commands in this guide from inside your OpenShift cluster": Clarify what we mean by "inside your OpenShift cluster".  And, I don't believe all commands that users will execute are from "inside your OpenShift cluster"?

**Comment by yeekangc** [comment]
@gkwan-ibm

**Comment by yeekangc** [comment]
The primary considerations were what I attempted to call out in/with #21 and #27.

**Comment by MaiHameed** [comment]
Red Hat has a sandbox version of OpenShift, which is essentially a free access to an OpenShift 4.4 cluster that will expire after 1 hour. I think it will work in the context of our guide: https://learn.openshift.com/playgrounds/openshift44/. This will solve:

> " Ensure you are using version 4.x because the Dockerfiles used in this guide use the --chown flag, which is incompatible with older versions of Docker": Can't parse this easily. The 4.x version is referring to what?

since the sandbox is version 4.4 so we don't need to have that disclaimer, and will solve: 

> "Make sure to run all commands in this guide from inside your OpenShift cluster": Clarify what we mean by "inside your OpenShift cluster". And, I don't believe all commands that users will execute are from "inside your OpenShift cluster"?

Since all commands will be run inside the web-based sandbox, making it clearer. Can we point to this sandbox in our guide or would you prefer that we keep pointing the users to other more permanent platforms?

> Call out the benefits of using Operators -- in this case, the OL Operator -- in the Intro section

We already have a paragraph introducing the Operator in the intro: https://draft-guides.mybluemix.net/guides/cloud-openshift-operator.html, is this sufficient? Or do you want a more specific explanation outlining the benefits vs non-operator deployment? @yeekangc

**Comment by yeekangc** [comment]
The guide itself should contain instructions that's applicable to OpenShift in general (agnostics of who is providing the OpenShift).

The playground may be a quick starting point or users can use OpenShift cluster that they have access too.  Should provide pointer to the free trial via OpenShift Online or e.g. OpenShift on IBM Cloud (https://www.ibm.com/cloud/openshift) as options.

As for benefits for using operators, the current Intro paragraph is alright as an introduction.  Then, it doesn't call out the benefits of using operators.  Should elaborate on the benefits.

**Comment by yeekangc** [comment]
Should queue up an item for covering service binding operator too.

**Comment by gkwan-ibm** [comment]
close
- all feedback were addressed
